/* 
 * Binance REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

pub enum CandlestickIntervals {
  _1m,
  _3m,
  _5m,
  _15m,
  _30m,
  _1h,
  _2h,
  _4h,
  _6h,
  _8h,
  _12h,
  _1d,
  _3d,
  _1w,
  _1M,
}

impl CandlestickIntervals {
  pub fn to_string(&self) -> String {
     use self::CandlestickIntervals::*;    
      match *self {
        _1m => "3m".into(),
        _3m => "3m".into(),
        _5m => "5m".into(),
        _15m => "15m".into(),
        _30m => "30m".into(),
        _1h => "1h".into(),
        _2h => "2h".into(),
        _4h => "4h".into(),
        _6h => "6h".into(),
        _8h => "8h".into(),
        _12h => "12h".into(),
        _1d => "1d".into(),
        _3d => "3d".into(),
        _1w => "1w".into(),
        _1M => "1M".into(),
      }
    }
}