/* 
 * Binance REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Errorcode {
  #[serde(rename = "code")]
  code: f32,
  #[serde(rename = "msg")]
  msg: String
}

impl Errorcode {
  pub fn new(code: f32, msg: String) -> Errorcode {
    Errorcode {
      code: code,
      msg: msg
    }
  }

  pub fn set_code(&mut self, code: f32) {
    self.code = code;
  }

  pub fn with_code(mut self, code: f32) -> Errorcode {
    self.code = code;
    self
  }

  pub fn code(&self) -> &f32 {
    &self.code
  }


  pub fn set_msg(&mut self, msg: String) {
    self.msg = msg;
  }

  pub fn with_msg(mut self, msg: String) -> Errorcode {
    self.msg = msg;
    self
  }

  pub fn msg(&self) -> &String {
    &self.msg
  }


}



