/* 
 * Binance REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RateLimitType {
}

impl RateLimitType {
  pub fn new() -> RateLimitType {
    RateLimitType {
    }
  }

}

// TODO enum 
// List of RateLimitType
//const (
//  
//  
//  
//)


