/* 
 * Binance REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Servertime {
  #[serde(rename = "serverTime")]
  server_time: String
}

impl Servertime {
  pub fn new(server_time: String) -> Servertime {
    Servertime {
      server_time: server_time
    }
  }

  pub fn set_server_time(&mut self, server_time: String) {
    self.server_time = server_time;
  }

  pub fn with_server_time(mut self, server_time: String) -> Servertime {
    self.server_time = server_time;
    self
  }

  pub fn server_time(&self) -> &String {
    &self.server_time
  }


}



