/* 
 * Binance REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Ticker24hrlist {
}

impl Ticker24hrlist {
  pub fn new() -> Ticker24hrlist {
    Ticker24hrlist {
    }
  }

}



